import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Burgernav from "./components/Burgenav/Burgernav";
import Subnav from "./components/Subnav/Subnav";
import Footer from "./components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
